### ISSUE TITLE
Fix text and icon color

### ISSUE THREAD

**Issue by npty** [axelarnetwork/webdocs#38]
We have dark text on dark background right now.

<img width="301" alt="Screen Shot 2565-02-14 at 14 34 44" src="https://user-images.githubusercontent.com/78221556/153820245-ed3c54e4-cb24-4340-aa4c-e52b25182a1d.png">

**Comment by ggutoski** [comment]
Thanks.  We're about to switch to a new docs framework.  This problem should disappear after the switch.
