### ISSUE TITLE
Documentation doesn't instruct to fund the validator account when registering a broadcaster

### ISSUE THREAD

**Issue by staketartare** [axelarnetwork/webdocs#53]
When following the official doc to setup a validator:
https://docs.axelar.dev/roles/validator/setup/register-broadcaster

The register command fails with error "account  XXX not found: key not found" (matching the validator account address)
This issue has been encountered by other people on Discord as well.
Funding the validator account solves the issue

It turns out there is two problems:
1/ The documentation doesn't instruct to fund the validator account, only the broadcaster account
2/ The error message is misleading, because the validator keys are there and properly setup. It should probably instead suggest the validator account needs to be funded?

**Comment by ggutoski** [comment]
Thank you!

> 1/ The documentation doesn't instruct to fund the validator account, only the broadcaster account

Good catch.  This will be fixed.

> 2/ The error message is misleading, because the validator keys are there and properly setup. It should probably instead suggest the validator account needs to be funded?

Unfortunately this behaviour is inherited from Cosmos SDK.  It is a common complaint.  Needs to be fixed upstream. :/

**Comment by staketartare** [comment]
Sounds good thanks! Makes sense for the SDK issue I actually just hit the same problem on another Cosmos chain.
